### ISSUE TITLE
[ENTRY] gachikoi

### ISSUE THREAD

**Issue by VTuberDictionary** [Madekuji/vtuberdictionary#13]
# Dictionary entry
For making new dictionary entries or updating existing ones. Please use one of these for each term. Do not use more than one term for each request.

### Term:
*(Insert word, phrase, or term here.)*
gachikoi

### Lexical category:
*(Is the word a noun, verb, adjective, or etc.?)*

### Japanese:
*(If the term is of Japanese origin, please enter the original writing in kanji and/or kana.)*

### IPA:
*(Insert the phonetic transcription here. You may use https://tophonetics.com/ (for American English) or https://shioya.fr/transcription_jp.html (for Japanese) to create it, and then http://ipa-reader.xyz/ to test it.)*

### Definition:
*(Insert definition here.)*

### Additional media:
*(Insert any additional media or materials such as images, YouTube videos or tweets that may be beneficial to explaining the term.)*

### Sources:
*(Insert any links to sources you used to create this definition.)*

---

- [x] Term
- [x] Lexical category
- [x] Japanese
- [x] IPA
- [x] Definition
- [x] Sample sentences
- [x] Additional media
- [x] Sources
- [x] Recorded speech
- [x] Add post

**Comment by Madekuji** [comment]
Lexical category:
noun, adjective

**Comment by Madekuji** [comment]
Japanese:
ガチ恋

**Comment by Madekuji** [comment]
IPA:
gatɕikoi

**Comment by Madekuji** [comment]
Sources:
- <https://hololive.wiki/wiki/Glossary>
- <https://jisho.org/word/%E3%82%AC%E3%83%81%E6%81%8B>
- <https://www.urbandictionary.com/define.php?term=gachikoi>
- <https://twitter.com/izzy___315/status/1133584777100050433>
- <https://www.reddit.com/r/VirtualYoutubers/comments/ice9e3/gachikoi_culture/>
- <https://www.reddit.com/r/Hololive/comments/k2dfz8/the_basic_hololive_jp_dictionary_for_newcomers/>
- <https://yumemipi.wordpress.com/2020/05/29/oshi-terms-101-a-guide/>
- <https://qqpy.tumblr.com/post/102764606876/guide-to-idol-otaku-phrases-on-japanese-twitter>

**Comment by Madekuji** [comment]
Additional media:
https://www.youtube.com/watch?v=OqtvVkA_aAQ

**Comment by Madekuji** [comment]
Sample sentences:

(noun)
I'd probably consider myself a Hoshikawa gachikoi.
Coco has no gachikois, that's a fact.
People might be a little quick calling themselves a gachikoi.

(adjective)
He's totally gachikoi for her.
I can't imagine myself being gachikoi for a VTuber, no matter how amazing they are.
It's really interesting when you get to that point where you find a VTuber that you end up being gachikoi for.

**Comment by Madekuji** [comment]
Definition:

(noun)
A fan who is seriously in love with a VTuber, idol, or actor. Originally an idol/ota term to describe a fan who is seriously or actually in love with an idol or actor.

(adjective)
The state of being a gachikoi or being seriously in love with a VTuber, idol, or actor. See gachikoi (noun).
