### ISSUE TITLE
[ENTRY] debut

### ISSUE THREAD

**Issue by VTuberDictionary** [Madekuji/vtuberdictionary#14]
# Dictionary entry
For making new dictionary entries or updating existing ones. Please use one of these for each term. Do not use more than one term for each request.

### Term:
*(Insert word, phrase, or term here.)*
debut

### Lexical category:
*(Is the word a noun, verb, adjective, or etc.?)*

### Japanese:
*(If the term is of Japanese origin, please enter the original writing in kanji and/or kana.)*

### IPA:
*(Insert the phonetic transcription here. You may use https://tophonetics.com/ (for American English) or https://shioya.fr/transcription_jp.html (for Japanese) to create it, and then http://ipa-reader.xyz/ to test it.)*

### Definition:
*(Insert definition here.)*

### Additional media:
*(Insert any additional media or materials such as images, YouTube videos or tweets that may be beneficial to explaining the term.)*

### Sources:
*(Insert any links to sources you used to create this definition.)*

---

- [x] Term
- [x] Lexical category
- [x] IPA
- [x] Definition
- [x] Sample sentences
- [x] Additional media
- [x] Sources
- [x] Recorded speech
- [x] Add post

**Comment by Madekuji** [comment]
Sources:
- <https://www.reddit.com/r/VirtualYoutubers/comments/i7gqk2/what_do_you_do_in_a_debut_stream/>
- <https://criticalreikan.medium.com/so-you-want-to-be-a-vtuber-6e7dc2a6df99>

**Comment by Madekuji** [comment]
IPA:
deɪˈbju

**Comment by Madekuji** [comment]
noun, verb

**Comment by Madekuji** [comment]
Additional media:
https://i.vgy.me/fE0PEe.png
![](https://i.vgy.me/fE0PEe.png)

**Comment by Madekuji** [comment]
Definition:

(noun)
A VTuber's introduction. This usually involves their first introductory video or stream that outlines who they are, what kind of content they make, and what goals they have as a VTuber.

(verb)
The act of a VTuber starting their career by making an introductory video or stream. See debut (noun).

(adjective)
Anything related to a debut video or stream, such as a debut original song, or a debut message.

**Comment by Madekuji** [comment]
Sample sentences:

(noun)
- Kizuna AI's debut definitely started everything.
- I don't think anyone could quite compare to his debut.
- After their debut, I'll be watching their career with great interest.

(verb)
- The art of debuting has definitely become a staple in VTuber culture.
- There's no one way to debut, but there is a way that only you can do.
- You can debut and re-debut as many times as you'd like; though most VTubers only do it once.

(adjective)
- Did you know that back then, Sora's debut stream only had 13 people watching?
- Starting off with a debut single or music video is a VSinger flex.
- She was speaking in multiple languages for her debut stream.
