### ISSUE TITLE
[ENTRY] anti

### ISSUE THREAD

**Issue by VTuberDictionary** [Madekuji/vtuberdictionary#24]
# Dictionary entry
For making new dictionary entries or updating existing ones. Please use one of these for each term. Do not use more than one term for each request.

### Term:
*(Insert word, phrase, or term here.)*
anti

### Lexical category:
*(Is the word a noun, verb, adjective, or etc.?)*

### Japanese:
*(If the term is of Japanese origin, please enter the original writing in kanji and/or kana.)*

### IPA:
*(Insert the phonetic transcription here. You may use https://tophonetics.com/ (for American English) or https://shioya.fr/transcription_jp.html (for Japanese) to create it, and then http://ipa-reader.xyz/ to test it.)*

### Definition:
*(Insert definition here.)*

### Sample sentences:
*(Insert different sentences that use the term here.)*

### Additional media:
*(Insert any additional media or materials such as images, YouTube videos or tweets that may be beneficial to explaining the term.)*

### Sources:
*(Insert any links to sources you used to create this definition.)*

---

- [x] Term
- [x] Lexical category
- [x] IPA
- [x] Definition
- [x] Sample sentences
- [x] Additional media
- [x] Sources
- [x] Recorded speech
- [x] Add post

**Comment by Madekuji** [comment]
Sources:

- <https://en.wikipedia.org/wiki/Anti-fan>
- <https://www.theguardian.com/theobserver/2007/apr/22/features.magazine47>
- <https://www.merriam-webster.com/dictionary/anti>
- <https://www.urbandictionary.com/define.php?term=anti>
- <https://www.reddit.com/r/Hololive/comments/jfdjzj/what_is_anti/>
- <https://en.wikipedia.org/wiki/List_of_gairaigo_and_wasei-eigo_terms>

**Comment by Madekuji** [comment]
Lexical category:
noun

**Comment by Madekuji** [comment]
IPA:
ˈenti

**Comment by Madekuji** [comment]
Definition:

Shorthand for "anti-fan" and Japanese English for "hater." In terms of VTubers, antis are people who focus on hating either a specific VTuber or group, or VTuber culture as a whole. Can also be used in other fandoms or cultures.

**Comment by Madekuji** [comment]
Additional media:
<https://i.vgy.me/hmR8oO.png>
![](https://i.vgy.me/hmR8oO.png)

**Comment by Madekuji** [comment]
Sample sentences:
- As fans, we ought to defend and protect against antis who'd do nothing but harass.
- It's honestly interesting to take a look at the thought process of an anti.
- It's one thing to be an anti, but totally another to be an anti doing illegal stuff.
