### ISSUE TITLE
[ENTRY] menba gentei

### ISSUE THREAD

**Issue by VTuberDictionary** [Madekuji/vtuberdictionary#30]
# Dictionary entry
For making new dictionary entries or updating existing ones. Please use one of these for each term. Do not use more than one term for each request.

### Term:
*(Insert word, phrase, or term here.)*
menba gentei

### Lexical category:
*(Is the word a noun, verb, adjective, or etc.?)*

### Japanese:
*(If the term is of Japanese origin, please enter the original writing in kanji and/or kana.)*

### IPA:
*(Insert the phonetic transcription here. You may use https://tophonetics.com/ (for American English) or https://shioya.fr/transcription_jp.html (for Japanese) to create it, and then http://ipa-reader.xyz/ to test it.)*

### Definition:
*(Insert definition here.)*

### Sample sentences:
*(Insert different sentences that use the term here.)*

### Additional media:
*(Insert any additional media or materials such as images, YouTube videos or tweets that may be beneficial to explaining the term.)*

### Sources:
*(Insert any links to sources you used to create this definition.)*

---

- [x] Term
- [x] Lexical category
- [x] Japanese
- [x] IPA
- [x] Definition
- [x] Sample sentences
- [x] Additional media
- [x] Sources
- [x] Recorded speech
- [ ] Add post

**Comment by Madekuji** [comment]
Lexical category:
adjective

**Comment by Madekuji** [comment]
Japanese:
メンバー限定

**Comment by Madekuji** [comment]
IPA:
meNbaːgeNtei

**Comment by Madekuji** [comment]
Sources:
- <https://www.reddit.com/r/Hololive/comments/icgxaq/a_guide_to_basic_written_hololive_japanese/>
- <https://hololive.wiki/wiki/Glossary>

**Comment by Madekuji** [comment]
Definition:

Translated as "members-only," signifying content exclusive to the VTuber's paid members. YouTube has a paid membership system for eligible YouTube channels that allows access to certain perks and content unavailable to public viewers; such content is classified as "members-only." This includes members-only messages, emotes, videos, streams, and other content.

**Comment by Madekuji** [comment]
Additional media:
<https://i.vgy.me/wIvHbG.png>
![](https://i.vgy.me/wIvHbG.png)

**Comment by Madekuji** [comment]
Sample sentences:
- Kanata said that she's doing a "menba gentei stream," I believe that means she'll do a members-only stream.
